apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: test-web-client
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: test-web-client
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/LyleXu/test-spring-web-client
      ref:
        branch: main
